# Generated by Django 2.1.7 on 2019-03-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='biography',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='shirtnumber',
            field=models.CharField(max_length=60),
        ),
    ]
