# Generated by Django 2.1.7 on 2019-03-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('formerclub', models.CharField(max_length=100)),
                ('biography', models.TextField()),
            ],
        ),
    ]
